project_id = "bzaqtvjereyqrymupapp"

[functions.twilio-sms-webhook]
verify_jwt = false

[functions.twilio-voice-webhook]
verify_jwt = false

[functions.twilio-voice-gather]
verify_jwt = false

[functions.send-email-verification]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.instagram-oauth-start]
verify_jwt = true

[functions.instagram-oauth-callback]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.instagram-send-message]
verify_jwt = true