project_id = "bzaqtvjereyqrymupapp"

[functions.deduct-credits]
verify_jwt = false

[functions.signicat-oauth-start]
verify_jwt = false

[functions.signicat-oauth-callback]
verify_jwt = false

[functions.vonage-sms-webhook]
verify_jwt = false

[functions.vonage-voice-webhook]
verify_jwt = false

[functions.vonage-voice-input]
verify_jwt = false

[functions.vonage-whatsapp-webhook]
verify_jwt = false

[functions.send-email-verification]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.instagram-oauth-start]
verify_jwt = true

[functions.instagram-oauth-callback]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.instagram-send-message]
verify_jwt = true

[functions.messenger-webhook]
verify_jwt = false

[functions.check-bokadirekt-availability]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = false